name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure Static Web Apps
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          action: "upload"
          app_location: "/"  # Set to the folder with your index.html
          output_location: "/"  # Set to the folder with your built files, if no build step, set to "/"
